networks:
  whoami:

services:
  traefik:
    networks:
      - whoami

  whoami:
    image: "traefik/whoami:latest"

    networks:
      - whoami

    labels:
      com.centurylinklabs.watchtower.enable: "${DEFAULT_WATCHTOWER_ENABLE}"
      com.centurylinklabs.watchtower.scope: "${DEFAULT_WATCHTOWER_SCOPE}"

      traefik.enable: true
      #traefik.http.routers.whoami.rule: "Host(`whoami${SECRET_SUFFIX}.${SECRET_DOMAIN}`)"
      #traefik.http.routers.whoami.entrypoints: "websecure"
      traefik.http.routers.whoami.tls.certresolver: "production"

      #traefik.http.routers.whoami-cf.rule: "Host(`whoami${SECRET_SUFFIX}.${SECRET_DOMAIN}`)"
      #traefik.http.routers.whoami-cf.entrypoints: "cloudflare"
      #traefik.http.routers.whoami-cf.service: "whoami-${PROJECT_NAME}"
      #traefik.http.routers.whoami-cf.tls.certresolver: "production"
